const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# IMOTARA_SIM_ARCH_V1';

// Lets the app build for the iOS Simulator on Apple Silicon.
//
// THE PROBLEM
// razorpay-core-pod (1.0.2) ships this in its podspec:
//
//   "pod_target_xcconfig":  { "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64" },
//   "user_target_xcconfig": { "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64" }
//
// `user_target_xcconfig` propagates to the APP target, not just the pod's own,
// so the whole project is forbidden from building arm64 for the simulator. On
// an Apple Silicon Mac that leaves no buildable simulator architecture at all,
// and the symptom is not an architecture error — it is Xcode listing NO
// concrete simulator destinations, so every build fails with:
//
//   error: Unable to find a destination matching the provided destination
//          specifier: { id:<the simulator you just booted> }
//
// which reads like a missing runtime or a stale simulator, and is neither.
//
// WHY IT IS SAFE TO REMOVE
// The exclusion is a leftover from the Intel era, when vendored frameworks
// had no arm64-simulator slice. Razorpay's does now:
//
//   ios/Pods/razorpay-pod/Pod/RazorpayStandard.xcframework/
//       ios-arm64_x86_64-simulator/     <- the slice the exclusion assumes is missing
//       ios-arm64/
//
// DEVICE AND STORE BUILDS ARE UNAFFECTED. The setting is scoped
// `[sdk=iphonesimulator*]`, so it never applied to iphoneos in the first
// place; removing it cannot change what ships.
//
// WHY IT REWRITES THE XCCONFIGS RATHER THAN build_settings
// The value arrives through the GENERATED xcconfig files that CocoaPods
// writes into Pods/Target Support Files. Deleting the key from
// `build_configurations.build_settings` in post_install does not touch those
// files, so the setting survives. The xcconfig is the thing that has to change.
//
// This has to be a plugin rather than a hand edit: ios/ is gitignored and
// regenerated by prebuild, and `pod install` rewrites these files from the
// podspec every time.
// Exported separately so it can be unit-tested without standing up Expo's mod
// pipeline (the plugin destructures withDangerousMod at require time, so a
// test cannot intercept it by patching the export).
function transformPodfile(contents) {
      if (contents.includes(MARKER)) return contents;

      // Anchor on the end of Expo's own post_install call, so our hook runs
      // after CocoaPods has written the files we are about to rewrite.
      const anchor = '      :ccache_enabled => ccache_enabled?(podfile_properties),\n    )';
      if (!contents.includes(anchor)) {
        throw new Error(
          'withIosSimulatorArch could not find the react_native_post_install call ' +
            'in the Podfile — the Expo template changed, and the simulator-arch fix ' +
            'would silently not apply.'
        );
      }

      const injection = `${anchor}

    ${MARKER}
    # razorpay-core-pod forbids arm64 for the simulator via user_target_xcconfig,
    # which on Apple Silicon leaves no buildable simulator arch and makes Xcode
    # offer no simulator destinations at all. See plugins/withIosSimulatorArch.js.
    # Scoped to iphonesimulator only — device and store builds are untouched.
    require 'pathname'
    support_files = Pathname.new(installer.sandbox.root) + 'Target Support Files'
    Dir.glob(support_files.to_s + '/**/*.xcconfig').each do |xcconfig|
      text = File.read(xcconfig)
      next unless text.include?('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
      File.write(
        xcconfig,
        text.gsub(/^EXCLUDED_ARCHS\\[sdk=iphonesimulator\\*\\].*$/, 'EXCLUDED_ARCHS[sdk=iphonesimulator*] = ')
      )
      Pod::UI.puts "[imotara] cleared simulator arch exclusion in #{File.basename(xcconfig)}"
    end`;

      return contents.replace(anchor, injection);
}

const withIosSimulatorArch = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      fs.writeFileSync(podfile, transformPodfile(fs.readFileSync(podfile, 'utf8')));
      return cfg;
    },
  ]);

module.exports = withIosSimulatorArch;
module.exports.transformPodfile = transformPodfile;
module.exports.MARKER = MARKER;
