const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** The breathing ambiences, by the resource name they get in res/raw. */
const SOUNDS = ['rain', 'ocean', 'bowl'];

// Ships the breathing ambiences as Android RAW RESOURCES.
//
// THE PROBLEM THIS EXISTS FOR
// On a release build, a `require()`d .mp3 could not be resolved to a URI on a
// real Galaxy A27, while the identical APK was fine on an emulator. Measured
// on the device:
//
//   Image.resolveAssetSource() -> { "__packager_asset": true, "uri": "", "scale": 1 }
//   Asset.fromModule()         -> uri: "", name: "bowl", type: "mp3", hash: "f6d326bd…"
//
// The metadata is correct and the files ARE in the APK — only the URI is
// empty. expo-av then calls ExpoAsset.downloadAsync with that empty string and
// rejects: "Unable to download asset from url:". Every track, every time, so
// the breathing exercise played in silence on hardware.
//
// Three JS-side fixes were tried and none worked (explicit Asset.fromModule +
// downloadAsync, and a migration to expo-audio); see pending_tasks.md O8.
//
// THE FIX
// Take JS asset resolution out of the path entirely. Android has a first-class
// place for bundled media — res/raw — addressable by a URI that needs no
// packager metadata at all:
//
//     android.resource://<applicationId>/raw/<name>
//
// expo-av plays fine from a URI; that is how TTS has always worked, and TTS
// audio was verified working on the same A27 the same day. So this uses the
// path that is known good on this device.
//
// WHY A PLUGIN: android/ is gitignored and regenerated by prebuild, so files
// copied in by hand do not survive. Same reasoning as withAndroidImeInsets.
//
// iOS IS NOT TOUCHED. The failure was only ever observed on Android, and the
// JS `require()` path stays in place for iOS — see MUSIC_SOURCES in
// BreathingModal.tsx. Do not "simplify" that into one code path without
// testing iOS on hardware first.
//
// ⚠️ res/raw names must be lowercase a-z0-9_ and carry no extension in the
// resource id. The three files are already named that way; a new one that is
// not will fail the Android build with a confusing aapt error, so the plugin
// checks and throws with a clear message instead.
const withAndroidRawSounds = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot;
      const srcDir = path.join(projectRoot, 'assets', 'sounds');
      const rawDir = path.join(platformRoot, 'app', 'src', 'main', 'res', 'raw');

      fs.mkdirSync(rawDir, { recursive: true });

      for (const name of SOUNDS) {
        if (!/^[a-z][a-z0-9_]*$/.test(name)) {
          throw new Error(
            `withAndroidRawSounds: "${name}" is not a valid Android resource name. ` +
              'res/raw names must be lowercase letters, digits and underscores, ' +
              'starting with a letter.'
          );
        }
        const from = path.join(srcDir, `${name}.mp3`);
        if (!fs.existsSync(from)) {
          throw new Error(
            `withAndroidRawSounds: expected ${from} to exist. The breathing ` +
              'ambiences are the source of truth for res/raw; if one was renamed, ' +
              'update SOUNDS in this plugin too.'
          );
        }
        fs.copyFileSync(from, path.join(rawDir, `${name}.mp3`));
      }

      return cfg;
    },
  ]);

module.exports = withAndroidRawSounds;
module.exports.SOUNDS = SOUNDS;
